body:
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.
          required: true

  - type: input
    id: repo
    attributes:
      label: Link to your website repo
      description: "In almost all cases, **we cannot help you if you don't provide this**."
      placeholder: ex. https://github.com/greenelab/greenelab.com
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version of Lab Website Template you are using
      description: See your `CITATION.cff` file.
      placeholder: ex. 1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe your issue in as much detail as possible. For example: What happened? What did you expect to happen? How can we reproduce the problem? What browser are you seeing the problem in?
      placeholder: Description
    validations:
      required: true
